[package]
name = "dead-mans-switch"
version = "0.1.0"
authors = ["eupn <eupn@protonmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.3"
anyhow = "1"
bdk = { version = "0.8.0", features = ["compiler", "key-value-db", "esplora"] }
tiny-bip39 = "0.8.0"
